[tool.mypy]
python_version = '3.11'

[tool.ruff]
extend-select = ["C4", "C90", "SIM", "TCH"]
ignore = ["SIM108"]

[tool.ruff.isort]
section-order = [
    "future",
    "standard-library",
    "third-party",
    "first-party",
    "local-folder",
]
