name: test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  pre-commit:
    name: Run tests & display coverage
    runs-on: ubuntu-latest
    permissions:
      # Gives the action the necessary permissions for publishing new
      # comments in pull requests.
      pull-requests: write
      # Gives the action the necessary permissions for pushing data to the
      # python-coverage-comment-action branch, and for editing existing
      # comments (to avoid publishing multiple comments in the same PR)
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: install graphviz
        uses: tlylt/install-graphviz@v1
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.11
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run pre-commit on all files
        run: pre-commit run --hook-stage pre-push
      - name: Coverage comment
        uses: py-cov-action/python-coverage-comment-action@v3
        with:
          GITHUB_TOKEN: ${{ github.token }}